# Color Classification

The color classification task is to predict the distinct color category based on the three input values for RGB (R: Red, G: Green, B: Blue) color code. Each of these three numbers is basically an integer ranging from 0 to 255 and these combined Red, Green & Blue values are used to generate a distinct solid color. The dataset contains 11 basic color categories for classification. These basic colors are Red, Green, Blue, Yellow, Orange, Pink, Purple, Brown, Grey, Black and White.

Import necessary libraries

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import accuracy_score

Load data into a dataframe

In [24]:
df = pd.read_csv('./data/data.csv')
df

red  green  blue  label
0      20    139   240   Blue
1     174     83    72  Brown
2     144    249   131  Green
3     168     25   156   Pink
4      30    182   136  Green
...   ...    ...   ...    ...
5002   26     26    26  Black
5003   27     27    27  Black
5004   28     28    28  Black
5005   29     29    29  Black
5006   30     30    30  Black

[5007 rows x 4 columns]

 Encode "label" column into numerical data using sklearn LabelEncoder

In [28]:
le = LabelEncoder()
le.fit(df['label'])
df['label'] = le.transform(df['label'])
df['label']

0       1
1       2
2       3
3       6
4       3
       ..
5002    0
5003    0
5004    0
5005    0
5006    0
Name: label, Length: 5007, dtype: int64

Split the data into train and test datasets with 80:20 ratio

In [29]:
features = df.copy()
labels = features.pop('label')
features = np.array(features)
labels = np.array(labels)

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2)
print('X_train',X_train)
print('y_train',y_train)
print('X_test',X_test)
print('y_test',y_test)



X_train [[ 28  67 150]
 [ 60  73  91]
 [237 227  32]
 ...
 [ 78  31 131]
 [123 202  48]
 [112 205 221]]
y_train [ 1  4 10 ...  7  3  1]
X_test [[165  27 225]
 [104 152 174]
 [165 212 199]
 ...
 [155 180 197]
 [ 65 208  86]
 [169 143 116]]
y_test [7 1 4 ... 1 3 2]


Install and import tensorflow library 

In [31]:
!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.layers import Dense

Build and compile the sequential model. The model has a input, a output and a hidden layer. Activation function of the hidden layer is relu. The model is optimized by the Adam optimizer.

In [48]:
model = tf.keras.Sequential([
  Dense(3),
  Dense(7,activation='relu'),
  Dense(11)
])

model.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

model(X_train[0:2],y_train[0:2])
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (2, 3)                    12        
                                                                 
 dense_16 (Dense)            (2, 7)                    28        
                                                                 
 dense_17 (Dense)            (2, 11)                   88        
                                                                 
Total params: 128
Trainable params: 128
Non-trainable params: 0
_________________________________________________________________


Train the model on the training dataset for 500 epochs

In [53]:

model.fit(X_train, y_train, epochs=500)


Epoch 1/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3579 - accuracy: 0.8604
Epoch 2/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8579
Epoch 3/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3588 - accuracy: 0.8577
Epoch 4/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3573 - accuracy: 0.8517
Epoch 5/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3618 - accuracy: 0.8599
Epoch 6/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8562
Epoch 7/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3614 - accuracy: 0.8547
Epoch 8/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3557 - accuracy: 0.8567
Epoch 9/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3516 - accuracy: 0.8602
Epoch 10/500
126/126 [==============================] - 1s 5ms/step - loss: 0.3531 - accura

126/126 [==============================] - 0s 2ms/step - loss: 0.3386 - accuracy: 0.8662
Epoch 82/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3387 - accuracy: 0.8689
Epoch 83/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3364 - accuracy: 0.8674
Epoch 84/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8682
Epoch 85/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3368 - accuracy: 0.8647
Epoch 86/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8687
Epoch 87/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8657
Epoch 88/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3360 - accuracy: 0.8672
Epoch 89/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3351 - accuracy: 0.8662
Epoch 90/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3388 - accuracy: 

126/126 [==============================] - 0s 2ms/step - loss: 0.3280 - accuracy: 0.8699
Epoch 161/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8699
Epoch 162/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3238 - accuracy: 0.8717
Epoch 163/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3276 - accuracy: 0.8692
Epoch 164/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3288 - accuracy: 0.8684
Epoch 165/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3273 - accuracy: 0.8649
Epoch 166/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3239 - accuracy: 0.8684
Epoch 167/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3241 - accuracy: 0.8737
Epoch 168/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3234 - accuracy: 0.8717
Epoch 169/500
126/126 [==============================] - 0s 3ms/step - loss: 0.3264 - a

126/126 [==============================] - 0s 2ms/step - loss: 0.3161 - accuracy: 0.8714
Epoch 240/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3180 - accuracy: 0.8732
Epoch 241/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3160 - accuracy: 0.8752
Epoch 242/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3163 - accuracy: 0.8749
Epoch 243/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3152 - accuracy: 0.8754
Epoch 244/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3159 - accuracy: 0.8749
Epoch 245/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3212 - accuracy: 0.8717
Epoch 246/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3163 - accuracy: 0.8727
Epoch 247/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3178 - accuracy: 0.8722
Epoch 248/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3177 - a

126/126 [==============================] - 0s 2ms/step - loss: 0.3164 - accuracy: 0.8729
Epoch 319/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3120 - accuracy: 0.8739
Epoch 320/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3131 - accuracy: 0.8739
Epoch 321/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3110 - accuracy: 0.8734
Epoch 322/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3107 - accuracy: 0.8742
Epoch 323/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3117 - accuracy: 0.8759
Epoch 324/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3118 - accuracy: 0.8759
Epoch 325/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3119 - accuracy: 0.8719
Epoch 326/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3128 - accuracy: 0.8764
Epoch 327/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3129 - a

126/126 [==============================] - 0s 2ms/step - loss: 0.3075 - accuracy: 0.8789
Epoch 398/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3113 - accuracy: 0.8744
Epoch 399/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3105 - accuracy: 0.8724
Epoch 400/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3095 - accuracy: 0.8777
Epoch 401/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3119 - accuracy: 0.8774
Epoch 402/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3083 - accuracy: 0.8784
Epoch 403/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3108 - accuracy: 0.8742
Epoch 404/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3066 - accuracy: 0.8789
Epoch 405/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3061 - accuracy: 0.8806
Epoch 406/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3083 - a

126/126 [==============================] - 0s 2ms/step - loss: 0.3094 - accuracy: 0.8749
Epoch 477/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3060 - accuracy: 0.8774
Epoch 478/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3049 - accuracy: 0.8792
Epoch 479/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3083 - accuracy: 0.8752
Epoch 480/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3094 - accuracy: 0.8772
Epoch 481/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3110 - accuracy: 0.8724
Epoch 482/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3064 - accuracy: 0.8787
Epoch 483/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3070 - accuracy: 0.8772
Epoch 484/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3069 - accuracy: 0.8794
Epoch 485/500
126/126 [==============================] - 0s 2ms/step - loss: 0.3051 - a

Predict the color category for the testing data and save the result in csv file

In [56]:
probability_model = tf.keras.Sequential([model, 
                                         tf.keras.layers.Softmax()])
probs = probability_model.predict(X_test)
predictions = np.argmax(probs, axis=1)
result = np.concatenate((X_test, np.expand_dims(predictions, axis=1)), axis=1)
result_df = pd.DataFrame(result,columns=['red', 'green', 'blue','label'])
result_df.to_csv('.prediction.csv',index = False)
result_df

32/32 [==============================] - 0s 3ms/step


red  green  blue  label
0     165     27   225      7
1     104    152   174      1
2     165    212   199      4
3      65    224   187      3
4      21    189   220      1
...   ...    ...   ...    ...
997    14     72     7      3
998   171    109   233      7
999   155    180   197      1
1000   65    208    86      3
1001  169    143   116      2

[1002 rows x 4 columns]

Evaluate the accuracy score of model using the predicted data

In [55]:
accuracy = accuracy_score(y_test, predictions)
print('Accuracy',accuracy)

Accuracy 0.8762475049900199
